# Generated by Django 3.1.4 on 2020-12-19 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryStatusTypeDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'dict_celery_status_type',
            },
        ),
        migrations.CreateModel(
            name='Schemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated date')),
            ],
            options={
                'db_table': 'schemas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemeColumnTypeDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'dict_scheme_column_type',
            },
        ),
        migrations.CreateModel(
            name='SeparatorDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'dict_separator',
            },
        ),
        migrations.CreateModel(
            name='StringCharacterDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'dict_string_character',
            },
        ),
        migrations.CreateModel(
            name='SchemeColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('input_from', models.IntegerField(blank=True, null=True, verbose_name='From')),
                ('input_to', models.IntegerField(blank=True, null=True, verbose_name='To')),
                ('order_id', models.IntegerField(default=0)),
                ('schemas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.schemas', verbose_name='Schemas')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.schemecolumntypedict', verbose_name='Type')),
            ],
            options={
                'db_table': 'scheme_columns',
                'ordering': ['order_id'],
            },
        ),
        migrations.AddField(
            model_name='schemas',
            name='col_separator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.separatordict', verbose_name='Separator'),
        ),
        migrations.AddField(
            model_name='schemas',
            name='col_string_char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.stringcharacterdict', verbose_name='String character'),
        ),
        migrations.AddField(
            model_name='schemas',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('file', models.FileField(upload_to='data_set/')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.celerystatustypedict', verbose_name='Status')),
            ],
            options={
                'db_table': 'data_set',
                'ordering': ['-created_at'],
            },
        ),
    ]
