# Generated by Django 3.1.4 on 2020-12-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemas',
            options={'ordering': ['-updated_at']},
        ),
    ]
