# Generated by Django 3.1.4 on 2020-12-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_dataset_schemas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='data_set/'),
        ),
    ]
