# Generated by Django 3.1.4 on 2020-12-22 15:50

import broker.services.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_dataset_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='file',
            field=models.FileField(blank=True, null=True, storage=broker.services.storages.PrivateMediaStorage(), upload_to=''),
        ),
    ]
